# Generated by Django 3.0.6 on 2021-10-09 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_auto_20211009_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
