# Generated by Django 3.0.6 on 2021-10-14 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_meal_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='users_like',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='meal',
            field=models.ManyToManyField(to='restaurant.Meal'),
        ),
    ]
