# Generated by Django 3.0.6 on 2021-10-14 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_auto_20211014_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='restaurant',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='meals',
            field=models.ManyToManyField(to='restaurant.Meal'),
        ),
    ]
